Repository osbuild/image-builder-frontend, pull requests merged in 2024-07, with the labels that each got.

#2191 src: Move content urls to const
  src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/RepositoriesStatus.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/RepositoryUnavailable.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/components/Empty.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/index.tsx
  src/Components/CreateImageWizardV2/steps/Snapshot/index.tsx
  src/Components/CreateImageWizardV2/utilities/betaPath.ts
  src/constants.ts
Labels: :white_check_mark: ready for review, :mage_man: Wizard

#2182 CreateDropdown: change navigation to specific image <HMS-4258>
  src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx
Labels: :white_check_mark: ready for review

#2207 wizard/compliance: re-enable stig profiles (HMS-4018)
  src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx
Labels: 🌟 best practice

#2212 constants: Update URLs
  src/constants.ts
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2170 Wizard: set status on Details step
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
Labels: :white_check_mark: ready for review

#2225 Wizard: enable nav items properly in Edit mode
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
  src/test/Components/CreateImageWizardV2/EditImageWizard.test.tsx
  src/test/fixtures/blueprints.ts
Labels: :white_check_mark: ready for review, :baby_bottle: simple, :exclamation: important

#2229 README: Update and clean up
  README.md
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2236 jest: Increase test timeout
  package.json
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :baby_bottle: simple

#2233 Wizard: fix blueprint unique name validation in Edit mode
  src/Components/CreateImageWizardV2/utilities/requestMapper.ts
  src/Components/CreateImageWizardV2/utilities/useValidation.tsx
  src/store/wizardSlice.ts
  src/test/fixtures/editMode.ts
Labels: :white_check_mark: ready for review, :baby_bottle: simple, :exclamation: important

#2232 Wizard: Fix repositories recommendations
  src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple, :mage_man: Wizard

#2241 test: Fix act warnings
  src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2242 test: Silence the DOM dump in test output
  src/test/setup.ts
Labels: :white_check_mark: ready for review

#2255 README: Add DOM dump silencing to `Test Guidelines`
  README.md
Labels: :white_check_mark: ready for review

#2252 devDeps: Bump msw from 2.3.1 to 2.3.2
  package-lock.json
  package.json
  src/mockServiceWorker.js
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2253 dependabot: Decrease open PR limit
  .github/dependabot.yml
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2256 README: Update Jest to Vitest
  README.md
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2270 README: Update readme after migrating to fec.config.js
  README.md
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2271 test: Remove deprecated flags from mocking
  src/test/Components/Blueprints/Blueprints.test.tsx
  src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.tsx
  src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2279 wizard/registration: Add missing article (typo)
  src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx
Labels: :baby_bottle: simple

#2281 Firstboot: validate shebang is defined (HMS-4458)
  src/Components/CreateImageWizard/CreateImageWizard.tsx
  src/Components/CreateImageWizard/steps/FirstBoot/index.tsx
  src/Components/CreateImageWizard/utilities/useValidation.tsx
  src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
Labels: 🌟 best practice

#2286 test: Move compliance On Recreate test to On Edit
  src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.tsx
  src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
  src/test/fixtures/editMode.ts
Labels: :white_check_mark: ready for review

#2287 Wizard: disable non-snapshot repositories when needed (HMS-4481)
  src/Components/CreateImageWizard/steps/Repositories/Repositories.tsx
  src/test/fixtures/repositories.ts
Labels: 🌟 best practice
