Repository osbuild/image-builder-frontend, pull requests merged in 2024-11, with the labels that each got.

#2497 Wizard: Move VMware radios into VMware checkbox
  src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
Labels: :white_check_mark: ready for review

#2513 devDeps: Manual bump msw from 2.4.9 to 2.4.10
  package-lock.json
  package.json
  src/mockServiceWorker.js
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2498 Wizard: Fix VMware select and unselect
  src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
  src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
Labels: :white_check_mark: ready for review

#2558 Konflux: Add rpms-signature-scan task (HMS-4948)
  .tekton/image-builder-frontend-pull-request.yaml
  .tekton/image-builder-frontend-push.yaml
Labels: 🌟 best practice

#2557 devDeps: Manually bump msw from 2.4.10 to 2.6.0
  package-lock.json
  package.json
  src/mockServiceWorker.js
Labels: :white_check_mark: ready for review

#2576 Wizard: handle dos scripts in first boot (HMS-4966)
  src/Components/CreateImageWizard/steps/FirstBoot/index.tsx
  src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
  src/test/fixtures/editMode.ts
Labels: 🌟 best practice

#2575 Wizard: Basic Timezone step (HMS-5009)
  src/Components/CreateImageWizard/CreateImageWizard.tsx
  src/Components/CreateImageWizard/steps/Timezone/components/TimezoneDropDown.tsx
  src/Components/CreateImageWizard/steps/Timezone/index.tsx
  src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
  src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
  src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
  src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
  src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
  src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
  src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
  src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx
  src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx
  src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
  src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
  src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
  src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
  src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx
  src/test/setup.ts
Labels: :white_check_mark: ready for review, 🌟 best practice

#2519 src: Add on prem blueprints import support (HMS-4683)
  package-lock.json
  package.json
  src/Components/Blueprints/ImportBlueprintModal.test.tsx
  src/Components/Blueprints/ImportBlueprintModal.tsx
  src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx
Labels: 🌟 best practice

#2620 ImagesTable: Fix image name spacing
  src/Components/ImagesTable/ImagesTable.tsx
Labels: :white_check_mark: ready for review

#2622 store/enhancedImageBuilderApi: handle empty error data (HMS-5049)
  src/store/enhancedImageBuilderApi.ts
Labels: 🌟 best practice

#2605 Konflux: Compare rpms-signature-scan with generated pipeline
  .tekton/image-builder-frontend-pull-request.yaml
  .tekton/image-builder-frontend-push.yaml
Labels: :white_check_mark: ready for review

#2621 ImagesTable: Unify pagination format with Repositories
  src/Components/ImagesTable/ImagesTable.tsx
Labels: :white_check_mark: ready for review
