Repository osbuild/image-builder-frontend, pull requests merged in 2024-10, with the labels that each got.

#2447 devDeps: Manually bump msw from 2.4.4 to 2.4.9
  package-lock.json
  package.json
  src/mockServiceWorker.js
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2425 src: Prefetch list of targets on hover of Create blueprint button
  src/Components/sharedComponents/ImageBuilderHeader.tsx
Labels: :white_check_mark: ready for review

#2492 Wizard: Fix incorrect aria labels
  src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2489 test: Update test naming
  src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2496 Wizard: Default to Included repos in package search
  src/Components/CreateImageWizard/steps/Packages/Packages.tsx
Labels: :white_check_mark: ready for review

#2495 Wizard: Fix repos toggle height
  src/Components/CreateImageWizard/steps/Packages/Packages.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2509 test: Move and re-enabled Details test (HMS-4658)
  src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
  src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
  src/test/Components/CreateImageWizard/wizardTestUtils.tsx
Labels: :white_check_mark: ready for review, 🌟 best practice

#2522 Wizard: move RHEL 9 beta out of preview (HMS-2234)
  src/Components/CreateImageWizard/steps/ImageOutput/ReleaseSelect.tsx
Labels: 🌟 best practice
