Repository osbuild/image-builder-frontend, pull requests merged in 2024-06, with the labels that each got.

#2050 Wizard V2: Custom Repositories refactor
  src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/RepositoryUnavailable.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/components/BulkSelect.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/components/Empty.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/components/Error.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/components/Loading.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/components/Utilities.ts
  src/Components/CreateImageWizardV2/steps/Repositories/index.tsx
  src/Components/CreateImageWizardV2/utilities/requestMapper.ts
  src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx
  src/test/fixtures/repositories.ts
  src/test/mocks/handlers.js
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard

#2110 test: Fix `'mockPackagesResults' not found`
  src/test/mocks/handlers.js
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2119 api: Add extra header to distinguish UI requests (HMS-4254)
  src/store/emptyImageBuilderApi.ts
Labels: :white_check_mark: ready for review, 🌟 best practice

#2097 V2Wizard: Add "clear" to package search (HMS-4182)
  src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard, 🌟 best practice

#2117 V2Wizard: add alert on snapshot step
  src/Components/CreateImageWizardV2/steps/Snapshot/index.tsx
Labels: :mage_man: V2 Wizard

#2070 src: Migrate remaining files to TypeScript (HMS-4063)
  README.md
  config/dev.webpack.config.js
  config/devel.webpack.config.js
  config/prod.webpack.config.js
  src/App.tsx
  src/AppEntry.tsx
  src/Components/CreateImageWizard/steps/imageOutput.js
  src/Router.tsx
  src/bootstrap.js
  src/bootstrap.tsx
  src/constants.ts
  src/entry.ts
  src/test/Components/CreateImageWizard/CreateImageWizard.test.js
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
  src/test/Components/LandingPage/LandingPage.test.tsx
  tsconfig.json
Labels: :white_check_mark: ready for review, 🌟 best practice

#2090 LandingPage: Make buttons disabled on Immutable (HMS-4182)
  src/Components/LandingPage/LandingPage.tsx
  src/Components/sharedComponents/ImageBuilderHeader.tsx
Labels: :white_check_mark: ready for review, 📄 blueprints, 🌟 best practice

#2140 test: Edit mode tests for repositories
  src/test/Components/Blueprints/Blueprints.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx
  src/test/fixtures/blueprints.ts
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard

#2167 Wizard: Cleanup after removing V1 (HMS-4309)
  package.json
  src/Utilities/checkRepositoriesAvailability.ts
  src/api.js
Labels: 🌟 best practice

#2168 ESLint: Merge .js and .ts configs to one file (HMS-4309)
  .eslintrc-typescript.yml
  .eslintrc.yml
  config/dev.webpack.config.js
  config/devel.webpack.config.js
  config/prod.webpack.config.js
Labels: :white_check_mark: ready for review, 🌟 best practice

#2164 V2Wizard: Hide package recommendations for CentOS
  src/Components/CreateImageWizardV2/steps/Packages/index.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple, :mage_man: V2 Wizard

#2152 test: Add edit mode tests (HMS-4303)
  src/test/Components/Blueprints/Blueprints.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx
  src/test/Components/CreateImageWizardV2/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
  src/test/Components/CreateImageWizardV2/steps/FirstBoot/Firstboot.test.tsx
  src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Oscap/Oscap.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Snapshot/Snapshot.test.tsx
  src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsTarget.test.tsx
  src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureTarget.test.tsx
  src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/GCPTarget.test.tsx
  src/test/fixtures/blueprints.ts
  src/test/fixtures/editMode.ts
  src/test/mocks/handlers.js
Labels: :white_check_mark: ready for review, 🌟 best practice

#2162 workflows: Replace Node 16 with Node 20
  .github/workflows/dev-checks.yml
Labels: ❔ question, :white_check_mark: ready for review, :baby_bottle: simple

#2133 Wizard: validate wizard with Redux Hook
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
  src/Components/CreateImageWizardV2/ValidatedTextInput.tsx
  src/Components/CreateImageWizardV2/steps/Details/index.tsx
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
  src/Components/CreateImageWizardV2/steps/FileSystem/index.tsx
  src/Components/CreateImageWizardV2/steps/Review/Footer/Footer.tsx
  src/Components/CreateImageWizardV2/utilities/requestMapper.ts
  src/Components/CreateImageWizardV2/utilities/useValidation.tsx
  src/store/wizardSlice.ts
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: needs rebase

#2171 test: Cleanup TargetEnvironment tests
  src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx
  src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/AwsTarget.test.tsx
  src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/AzureTarget.test.tsx
  src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/TargetEnvironment.test.tsx
Labels: :white_check_mark: ready for review

#2102 buildImageButton: add support of building image with mulitple targets <HMS-4066>
  src/Components/Blueprints/BuildImagesButton.tsx
  src/Components/ImagesTable/EmptyState.tsx
  src/test/Components/Blueprints/Blueprints.test.tsx
  src/test/fixtures/blueprints.ts
  src/test/fixtures/editMode.ts
  src/test/mocks/handlers.js
Labels: :white_check_mark: ready for review, 📄 blueprints

#2177 Wizard: Add Lightspeed to package recommendations (HMS-4340)
  src/Components/CreateImageWizardV2/steps/Packages/PackageRecommendations.tsx
  src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
Labels: :white_check_mark: ready for review, :mage_man: Wizard, 🌟 best practice

#2178 Wizard: validate uniqueness of Blueprint name (HMS-3801)
  src/Components/CreateImageWizardV2/ValidatedTextInput.tsx
  src/Components/CreateImageWizardV2/steps/Details/index.tsx
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
  src/Components/CreateImageWizardV2/utilities/useValidation.tsx
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Oscap/Oscap.test.tsx
  src/test/fixtures/blueprints.ts
  src/test/mocks/handlers.js
Labels: 🌟 best practice
