Repository osbuild/image-builder-frontend, pull requests merged in 2024-08, with the labels that each got.

#2309 Wizard: Replace `isBeta()` with conditional flag (HMS-4513)
  src/Components/CreateImageWizard/steps/Packages/index.tsx
Labels: 🌟 best practice

#2291 createImage: change resolution to be able to see buttons in create image wizard (HMS-4485)
  src/Components/CreateImageWizard/CreateImageWizard.scss
  src/Components/CreateImageWizard/CreateImageWizard.tsx
Labels: 🌟 best practice

#2311 Wizard: Update docs after move to new preview (HMS-4513)
  src/Components/CreateImageWizard/steps/Packages/Packages.tsx
  src/Components/CreateImageWizard/steps/Repositories/RepositoriesStatus.tsx
  src/Components/CreateImageWizard/steps/Repositories/RepositoryUnavailable.tsx
  src/Components/CreateImageWizard/steps/Repositories/components/Empty.tsx
  src/Components/CreateImageWizard/steps/Repositories/index.tsx
  src/Components/CreateImageWizard/steps/Snapshot/index.tsx
  src/Components/CreateImageWizard/utilities/betaPath.ts
Labels: :white_check_mark: ready for review, :mage_man: Wizard, 🌟 best practice

#2319 Blueprint: show basic version diff (HMS-4511)
  api/schema/imageBuilder.yaml
  src/Components/Blueprints/BlueprintDiffModal.tsx
  src/Components/ImagesTable/ImagesTableToolbar.tsx
  src/store/imageBuilderApi.ts
Labels: :white_check_mark: ready for review, 🌟 best practice

#2332 vitest: Disable `fileParallelism`
  vitest.config.ts
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2328 Wizard: Fix information rendered in package recommendations
  src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple, :mage_man: Wizard

#2338 testUtils: Merge `renderCustomRoutesWithReduxRouter` and `renderWithReduxRouter`
  src/Components/Blueprints/ImportBlueprintModal.test.tsx
  src/test/Components/Blueprints/Blueprints.test.tsx
  src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx
  src/test/Components/ImagesTable/ImagesTable.test.tsx
  src/test/Components/LandingPage/LandingPage.test.tsx
  src/test/testUtils.js
Labels: :white_check_mark: ready for review

#2341 Wizard: Add eslint-disable to useEffect
  src/Components/CreateImageWizard/steps/Details/index.tsx
  src/Components/CreateImageWizard/steps/Oscap/index.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2337 test: Move clicking helper functions to `wizardTestUtils`
  src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.tsx
  src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.tsx
  src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx
  src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
  src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
  src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
  src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
  src/test/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.test.tsx
  src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
  src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
  src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
  src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx
  src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
  src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
  src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
  src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
  src/test/Components/CreateImageWizard/wizardTestUtils.tsx
  src/test/testUtils.js
Labels: :white_check_mark: ready for review

#2321 devDeps: bump vitest and @vitest/coverage-v8
  package-lock.json
  package.json
  vitest.config.ts
Labels: dependencies, :white_check_mark: ready for review, :baby_bottle: simple

#2347 test: Clean up FSC tests
  src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
Labels: :white_check_mark: ready for review

#2361 test: Clean up Registration tests and enable a test
  src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
Labels: :white_check_mark: ready for review

#2357 test: Clean up AWS tests
  src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
Labels: :white_check_mark: ready for review

#2356 test: Clean up GCP tests
  src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
Labels: :white_check_mark: ready for review

#2360 test: Cleanup Image output tests
  src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
Labels: :white_check_mark: ready for review

#2366 Wizard: Fix disable Next on Registration step
  src/Components/CreateImageWizard/CreateImageWizard.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple, :mage_man: Wizard

#2371 test: Cleanup Azure tests
  src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.tsx
  src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
Labels: :white_check_mark: ready for review

#2378 Wizard: Update Amplitude tracking
  src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx
  src/Components/CreateImageWizard/steps/Review/Footer/CreateDropdown.tsx
  src/constants.ts
Labels: :white_check_mark: ready for review

#2379 createImageWizard: change the default name of bllueprint
  src/Components/CreateImageWizard/steps/Details/index.tsx
  src/Components/CreateImageWizard/utilities/generateDefaultName.ts
Labels: :mage_man: Wizard, :bangbang: lint errors

#2305 Wizard: Validate snapshot date with useValidation
  src/Components/CreateImageWizard/CreateImageWizard.tsx
  src/Components/CreateImageWizard/steps/Snapshot/Snapshot.tsx
  src/Components/CreateImageWizard/utilities/useValidation.tsx
  src/Components/CreateImageWizard/validators.ts
Labels: :wrench: needs work, :mage_man: Wizard
