Repository osbuild/image-builder-frontend, pull requests merged in 2024-01, with the labels that each got.

#1525 Travis: Disable npm cache
  .travis.yml
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1522 ESLint: Temporarily disable non actionable rules
  .eslintrc.yml
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1517 deps: Bump @redhat-cloud-services/frontend-components to 4.2.1
  package-lock.json
  package.json
Labels: dependencies, :white_check_mark: ready for review

#1514 app: useEffect warning fixes
  src/App.js
  src/Components/CreateImageWizard/formComponents/AWSSourcesSelect.js
  src/Components/CreateImageWizard/formComponents/ActivationKeys.js
  src/Components/CreateImageWizard/formComponents/AzureSourcesSelect.js
  src/Components/CreateImageWizard/formComponents/FileSystemConfigButtons.js
  src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js
  src/Components/CreateImageWizard/formComponents/MountPoint.js
Labels: needs rebase

#1541 Oscap: convert oscap javaScript file to typeScript file
  src/Components/CreateImageWizard/formComponents/Oscap.tsx
Labels: :white_check_mark: ready for review

#1553 V2Wizard: Fix wizard reset action
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
Labels: needs rebase, :white_check_mark: ready for review

#1563 test: Replace `.getBy` queries by awaited `.findBy`
  src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.js
  src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js
  src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js
  src/test/Components/CreateImageWizard/CreateImageWizard.test.js
  src/test/Components/CreateImageWizard/formComponents/TargetEnvironment.test.js
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
  src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx
  src/test/Components/ImagesTable/ImagesTable.test.js
  src/test/Components/LandingPage/LandingPage.test.js
  src/test/Components/ShareImageModal/ShareImageModal.test.js
Labels: :white_check_mark: ready for review

#1504 Wizard: Indicate disabled packages
  src/Components/CreateImageWizard/formComponents/Packages.js
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1559 V2Wizard: add oscap to wizard2
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
  src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx
  src/Components/CreateImageWizardV2/steps/Oscap/OscapProfileInformation.tsx
  src/Components/CreateImageWizardV2/steps/Oscap/index.tsx
  src/store/wizardSlice.ts
  src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx
Labels: :white_check_mark: ready for review

#1574 feat(HMS-3391): add blueprint onclick handler
  src/Components/Blueprints/BlueprintCard.tsx
  src/Components/Blueprints/BlueprintsSideBar.tsx
  src/Components/ImagesTable/ImagesTable.tsx
  src/Components/LandingPage/LandingPage.tsx
  src/test/Components/Blueprints/Blueprints.test.js
  src/test/fixtures/blueprints.ts
  src/test/mocks/handlers.js
Labels: :white_check_mark: ready for review

#1570 V2Wizard: add Details step to wizrd2
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
  src/Components/CreateImageWizardV2/ValidatedTextInput.tsx
  src/Components/CreateImageWizardV2/steps/Details/index.tsx
  src/Components/CreateImageWizardV2/validators.ts
  src/store/wizardSlice.ts
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :white_check_mark: ready for review

#1593 test: Repositories step review
  src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js
  src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Labels: :white_check_mark: ready for review

#1595 Wizard: Temporarily disable custom packages search
  src/Components/CreateImageWizard/formComponents/Packages.js
Labels: :white_check_mark: ready for review

#1594 Wizard: Temporarily disable Recreate for images with custom repositories
  src/Components/CreateImageWizard/formComponents/CustomButtons.js
  src/Components/CreateImageWizard/formComponents/ReviewStep.js
Labels: :white_check_mark: ready for review

#1596 test: Remove debugging statement and change `getBy` query to `findBy`
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1597 ESLint: Add no-debugging-utils rule
  src/test/.eslintrc
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1598 test: Enable blueprint description test
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1586 Resolve Controlled Component Error by Initializing with Empty Strings
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx
  src/store/wizardSlice.ts
Labels: :white_check_mark: ready for review
