Repository osbuild/image-builder-frontend, pull requests merged in 2024-05, with the labels that each got.

#2041 V2Wizard: Expandable to alert for disabled EPEL repo
  src/Components/CreateImageWizardV2/steps/Repositories/index.tsx
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard

#2044 scripts: Run parts of `api` script in correct order
  package.json
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2045 V2 Wizard: Expose OCI images in stable (HMS-2781)
  src/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.tsx
Labels: 🌟 best practice

#2049 test: Replace 'rhel-94' with a constant
  src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx
  src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx
  src/test/fixtures/blueprints.ts
  src/test/fixtures/composes.ts
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2054 Utilities: Migrate remaining files to TypeScript (HMS-4063)
  src/Components/CreateImageWizard/steps/imageOutputStepMapper.js
  src/Components/CreateImageWizardV2/utilities/checkRepositoriesAvailability.ts
  src/Utilities/checkRepositoriesAvailability.ts
  src/Utilities/edge.ts
  src/Utilities/isRhel.ts
  src/Utilities/path.ts
  src/Utilities/releaseToVersion.ts
  src/Utilities/useGetEnvironment.ts
  src/Utilities/useProvisioningPermissions.ts
Labels: :white_check_mark: ready for review, 🌟 best practice

#2048 V2Wizard: Hide first boot from review step (HMS-3582)
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStep.tsx
  src/Utilities/useBetaFlag.ts
Labels: :wrench: needs work, 🌟 best practice

#2059 V2Wizard: Fix repo/description in review table of package on Edit
  src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
  src/Components/CreateImageWizardV2/steps/Packages/components/PackageInfoNotAvailablePopover.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard

#2064 LandingPage / ImagesTable: Set max width for the ImagesTable
  src/Components/ImagesTable/ImagesTable.tsx
  src/Components/LandingPage/LandingPage.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2063 V2Wizard: Make e-mail validation case insensitive
  src/Components/CreateImageWizardV2/validators.ts
Labels: :white_check_mark: ready for review, :baby_bottle: simple, :mage_man: V2 Wizard

#2060 src/constants: Use major rhel distros by default
  src/constants.js
  src/test/Components/ImagesTable/ImagesTable.test.tsx
  src/test/fixtures/architectures.ts
Labels: :bricks: blocked

#2058 Blueprints: Fix snapshots + latest release
  src/Components/CreateImageWizardV2/utilities/requestMapper.ts
Labels: :white_check_mark: ready for review, 📄 blueprints

#1928 Blueprints: Add import Wizard (HMS-3690)
  src/Components/Blueprints/ImportBlueprintModal.test.tsx
  src/Components/Blueprints/ImportBlueprintModal.tsx
  src/Components/CreateImageWizardV2/ImportImageWizard.tsx
  src/Components/CreateImageWizardV2/utilities/requestMapper.ts
  src/Components/CreateImageWizardV2/validators.ts
  src/Components/sharedComponents/ImageBuilderHeader.tsx
  src/Router.js
Labels: 🌟 best practice

#2093 WizardV2: fix google account typo
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Gcp/index.tsx
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#2066 Status.tsx: show as many different error types as possible (HMS-1442)
  src/Components/ImagesTable/Status.tsx
Labels: 🌟 best practice

#2104 V2Wizard: Fix pagination on Packages step (useMemo)
  src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple
