Repository osbuild/image-builder-frontend, pull requests merged in 2024-03, with the labels that each got.

#1714 V2Wizard/test: Add autofocus and enable Keyboard accessibility tests (HMS-2781)
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/index.tsx
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Gcp/index.tsx
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :white_check_mark: ready for review, 🌟 best practice

#1702 test: Re-enable part of AWS tests (HMS-2781)
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :white_check_mark: ready for review, 🌟 best practice

#1706 V2Wizard/test: Fix bug on registration step and enable tests (HMS-2781)
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :white_check_mark: ready for review

#1722 V2Wizard: Clean up OSCAP info (HMS-2781)
  src/Components/CreateImageWizardV2/steps/Oscap/OscapProfileInformation.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple, :mage_man: V2 Wizard, 🌟 best practice

#1730 V1/V2Wizard: Capitalise ID on Azure step
  src/Components/CreateImageWizard/formComponents/AzureSourcesSelect.js
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureSourcesSelect.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1718 test: Remove "Click through all" (HMS-2781)
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :white_check_mark: ready for review, 🌟 best practice

#1723 V2Wizard: Move OSCAP alert outside of OscapProfileInformation (HMS-2781)
  src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx
  src/Components/CreateImageWizardV2/steps/Oscap/OscapProfileInformation.tsx
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard, 🌟 best practice

#1729 V2Wizard: Move FormGroup outside of ActivationKeyInformation (HMS-2781)
  src/Components/CreateImageWizardV2/steps/Registration/ActivationKeyInformation.tsx
  src/Components/CreateImageWizardV2/steps/Registration/index.tsx
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard, 🌟 best practice

#1732 CI: Drop SonarQube and Schutzbot in favor of Snyk (HMS-3696)
  .github/workflows/trigger-gitlab.yml
  .gitlab-ci.yml
  schutzbot/RH-IT-Root-CA.keystore
  schutzbot/sonarqube.sh
  schutzbot/terraform
  schutzbot/update_github_status.sh
Labels: 🌟 best practice

#1742 change the import path for MajorReleasesLifecyclesChart
  src/Components/CreateImageWizardV2/steps/ImageOutput/ReleaseLifecycle.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
Labels: :mage_man: V2 Wizard

#1743 V2Wizard: Remove aspectRatio
  src/Components/CreateImageWizardV2/steps/ImageOutput/ReleaseLifecycle.tsx
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard

#1747 test: Increase timeout for CreateImageWizard test
  src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1752 Blueprints table: Add title (HMS-3385)
  src/Components/ImagesTable/ImagesTable.tsx
Labels: 🌟 best practice

#1763 V2Wizard: Replace h2 heading with h1 and sizing (HMS-2781)
  src/Components/CreateImageWizardV2/steps/Details/index.tsx
  src/Components/CreateImageWizardV2/steps/ImageOutput/index.tsx
  src/Components/CreateImageWizardV2/steps/Oscap/index.tsx
  src/Components/CreateImageWizardV2/steps/Packages/index.tsx
  src/Components/CreateImageWizardV2/steps/Registration/index.tsx
  src/Components/CreateImageWizardV2/steps/Repositories/index.tsx
  src/Components/CreateImageWizardV2/steps/Review/index.tsx
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/index.tsx
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Gcp/index.tsx
Labels: :white_check_mark: ready for review, 🌟 best practice

#1739 V2Wizard: Update repository icons and names on Packages step (HMS-2864)
  src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
  src/constants.js
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard, 🌟 best practice

#1758 Blueprints Table: Add "new" alert
  src/Components/LandingPage/LandingPage.tsx
  src/Components/LandingPage/NewAlert.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1772 Router: Hotfix to update experimental flag
  src/Router.js
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1765 V2 Wizard Tests: Add tests for release and architecture
  src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/TargetEnvironment.test.tsx
  src/test/fixtures/architectures.ts
Labels: :white_check_mark: ready for review

#1658 V2 Wizard: Add File System Configuration Step (HMS-2781)
  package-lock.json
  package.json
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
  src/Components/CreateImageWizardV2/EditImageWizard.tsx
  src/Components/CreateImageWizardV2/UsrSubDirectoriesDisabled.tsx
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemAutomaticPartitionInformation.tsx
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemPartition.tsx
  src/Components/CreateImageWizardV2/steps/FileSystem/index.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
  src/Components/CreateImageWizardV2/utilities/requestMapper.tsx
  src/store/wizardSlice.ts
  src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx
  src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx
  src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/TargetEnvironment.test.tsx
Labels: 🌟 best practice

#1786 Wizard: Add FSC alert for bare metal images
  src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js
Labels: :magic_wand: enhancement, :white_check_mark: ready for review

#1787 V2Wizard: Add FSC alert for bare metal images
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
Labels: :magic_wand: enhancement, :mage_man: V2 Wizard

#1777 V2Wizard: Add partition function (HMS-3752)
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
  src/store/wizardSlice.ts
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard, 🌟 best practice

#1793 deps: Pin @types/uuid
  package-lock.json
  package.json
Labels: dependencies, :white_check_mark: ready for review

#1778 V2Wizard: fix remove partition funtionallity (HMS-3753)
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
  src/store/wizardSlice.ts
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard, 🌟 best practice

#1798 V1 Wizard: Add search parameter for arch selection (HMS-3684)
  src/Components/CreateImageWizard/formComponents/ArchSelect.js
  src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Labels: 🌟 best practice

#1789 V2Wizard: change default table when user choose manual cunfiguration
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemPartition.tsx
  src/store/wizardSlice.ts
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard

#1800 V2Wizard: Disable changing of root partition
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard

#1805 V2 Wizard: Add search parameter for arch selection (HMS-3684)
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
  src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple, 🌟 best practice

#1771 Blueprints: keep blueprint card selected after editing (HMS-3385)
  src/Components/Blueprints/BlueprintCard.tsx
Labels: :wrench: needs work, 📄 blueprints, 🌟 best practice

#1807 Blueprints: Make Blueprints! alert dismissible
  src/Components/LandingPage/NewAlert.tsx
Labels: :white_check_mark: ready for review, 📄 blueprints

#1817 V1Wizard: Add search parameter for target selection (HMS-3684)
  src/Components/CreateImageWizard/formComponents/TargetEnvironment.js
  src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Labels: :white_check_mark: ready for review, 🌟 best practice

#1816 V2Wizard: Add search parameter for target selection (HMS-3684)
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
  src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard, 🌟 best practice

#1822 V1Wizard: masked services -> disabled services (HMS-3661)
  src/Components/CreateImageWizard/CreateImageWizard.js
  src/Components/CreateImageWizard/formComponents/Oscap.tsx
  src/Components/CreateImageWizard/formComponents/OscapProfileInformation.tsx
  src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js
  src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx
  src/test/fixtures/oscap.ts
Labels: 🌟 best practice

#1794 Images: add popover when the image is outdated (HMS-3763)
  src/Components/ImagesTable/Instance.tsx
Labels: 🌟 best practice

#1832 Blueprint: Validate Blueprint name is not empty (HMS-3801)
  src/Components/CreateImageWizardV2/steps/Details/index.tsx
  src/Components/CreateImageWizardV2/validators.ts
  src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx
  src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx
Labels: 🌟 best practice

#1776 V2Wizard: fix partition at review step (HMS-3754)
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
  src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemPartition.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
  src/store/wizardSlice.ts
Labels: :mage_man: V2 Wizard, 🌟 best practice

#1847 Wizard: Resolve deprecation warning in test output
  src/Components/CreateImageWizard/formComponents/ReleaseLifecycle.tsx
  src/Components/CreateImageWizardV2/steps/ImageOutput/ReleaseLifecycle.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1848 templates/testing: Update sel testing image frontend (IQE-2748)
  deploy/iqe-trigger-integration.yml
Labels: 🌟 best practice

#1860 V2Wizard: Add test IDs to Packages step
  src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
Labels: :white_check_mark: ready for review
