Repository osbuild/image-builder-frontend, pull requests merged in 2024-02, with the labels that each got.

#1587 V2Wizard: Review step
  src/Components/CreateImageWizardV2/CreateImageWizard.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStep.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
  src/Components/CreateImageWizardV2/steps/Review/index.tsx
  src/store/helpers.ts
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :white_check_mark: ready for review

#1623 feat(HMS-3555) V2Wizard: fix ReleaseLifecycle component in the Review step
  src/Components/CreateImageWizard/formComponents/ReleaseLifecycle.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
Labels: :white_check_mark: ready for review

#1636 feat(HMS-3566) V2Wizrd: fix titles at aws step
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsAccountId.tsx
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx
Labels: :white_check_mark: ready for review

#1642 Wizard: Fix dates in Release Lifecycle text on the Review step
  src/Components/CreateImageWizard/formComponents/ReleaseLifecycle.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1643 Wizard: Remove aspect ratio for chart
  src/Components/CreateImageWizard/formComponents/ReleaseLifecycle.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1611 feat(HMS-3500) V2Wizrd: add kernel and services data
  src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx
  src/Components/CreateImageWizardV2/steps/Oscap/OscapProfileInformation.tsx
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
  src/store/wizardSlice.ts
  src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx
  src/test/fixtures/oscap.ts
Labels: :white_check_mark: ready for review

#1650 README: Link to osbuild-getting-started
  README.md
Labels: :baby_bottle: simple

#1678 test: Up timeout for 'image name invalid for more than 63 chars'
  src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1681 Blueprints: Add guest-image and vsphere-ova to requestMapper
  src/Components/CreateImageWizardV2/utilities/requestMapper.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple, 📄 blueprints

#1641 feat(HMS-3567): fix cleanup of Reource Group
  src/Components/CreateImageWizard/formComponents/AzureSourcesSelect.js
Labels: :white_check_mark: ready for review

#1631 feat(HMS-3515): Change blueprint cards to be clickable
  src/Components/Blueprints/BlueprintCard.tsx
  src/Components/Blueprints/BlueprintsSideBar.tsx
  src/Components/Blueprints/DeleteBlueprintModal.tsx
  src/Components/sharedComponents/ImageBuilderHeader.tsx
  src/test/Components/Blueprints/Blueprints.test.js
  src/test/fixtures/blueprints.ts
Labels: :white_check_mark: ready for review

#1634 feat(HMS-3553) V2Wizard: fix source name at review step when target is AWS
  src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
  src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsAccountId.tsx
Labels: :white_check_mark: ready for review

#1694 test: Remove `@ts-ignore` comments
  src/test/Components/CreateImageWizardV2/CreateImageWizard.azure.test.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple

#1701 V2Wizard: Remove bulk select and refresh button from the Packages step
  src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
  src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
Labels: :white_check_mark: ready for review, :baby_bottle: simple, :mage_man: V2 Wizard

#1703 V2Wizard/Packages: Add tests for requests
  src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx
Labels: :white_check_mark: ready for review, :mage_man: V2 Wizard
